# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/epiglottis/Code/armada-engine-prototype

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/epiglottis/Code/armada-engine-prototype

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/epiglottis/Code/armada-engine-prototype/CMakeFiles /home/epiglottis/Code/armada-engine-prototype//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/epiglottis/Code/armada-engine-prototype/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named Sandbox

# Build rule for target.
Sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sandbox
.PHONY : Sandbox

# fast build rule for target.
Sandbox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/build
.PHONY : Sandbox/fast

#=============================================================================
# Target rules for targets named debug_sources

# Build rule for target.
debug_sources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug_sources
.PHONY : debug_sources

# fast build rule for target.
debug_sources/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/build
.PHONY : debug_sources/fast

Sources/Engine/AssetSystem/AssetSystem.o: Sources/Engine/AssetSystem/AssetSystem.cc.o
.PHONY : Sources/Engine/AssetSystem/AssetSystem.o

# target to build an object file
Sources/Engine/AssetSystem/AssetSystem.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/AssetSystem/AssetSystem.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/AssetSystem/AssetSystem.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/AssetSystem/AssetSystem.cc.o
.PHONY : Sources/Engine/AssetSystem/AssetSystem.cc.o

Sources/Engine/AssetSystem/AssetSystem.i: Sources/Engine/AssetSystem/AssetSystem.cc.i
.PHONY : Sources/Engine/AssetSystem/AssetSystem.i

# target to preprocess a source file
Sources/Engine/AssetSystem/AssetSystem.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/AssetSystem/AssetSystem.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/AssetSystem/AssetSystem.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/AssetSystem/AssetSystem.cc.i
.PHONY : Sources/Engine/AssetSystem/AssetSystem.cc.i

Sources/Engine/AssetSystem/AssetSystem.s: Sources/Engine/AssetSystem/AssetSystem.cc.s
.PHONY : Sources/Engine/AssetSystem/AssetSystem.s

# target to generate assembly for a file
Sources/Engine/AssetSystem/AssetSystem.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/AssetSystem/AssetSystem.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/AssetSystem/AssetSystem.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/AssetSystem/AssetSystem.cc.s
.PHONY : Sources/Engine/AssetSystem/AssetSystem.cc.s

Sources/Engine/Camera/Camera.o: Sources/Engine/Camera/Camera.cc.o
.PHONY : Sources/Engine/Camera/Camera.o

# target to build an object file
Sources/Engine/Camera/Camera.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Camera/Camera.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Camera/Camera.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Camera/Camera.cc.o
.PHONY : Sources/Engine/Camera/Camera.cc.o

Sources/Engine/Camera/Camera.i: Sources/Engine/Camera/Camera.cc.i
.PHONY : Sources/Engine/Camera/Camera.i

# target to preprocess a source file
Sources/Engine/Camera/Camera.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Camera/Camera.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Camera/Camera.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Camera/Camera.cc.i
.PHONY : Sources/Engine/Camera/Camera.cc.i

Sources/Engine/Camera/Camera.s: Sources/Engine/Camera/Camera.cc.s
.PHONY : Sources/Engine/Camera/Camera.s

# target to generate assembly for a file
Sources/Engine/Camera/Camera.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Camera/Camera.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Camera/Camera.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Camera/Camera.cc.s
.PHONY : Sources/Engine/Camera/Camera.cc.s

Sources/Engine/Engine.o: Sources/Engine/Engine.cc.o
.PHONY : Sources/Engine/Engine.o

# target to build an object file
Sources/Engine/Engine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Engine.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Engine.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Engine.cc.o
.PHONY : Sources/Engine/Engine.cc.o

Sources/Engine/Engine.i: Sources/Engine/Engine.cc.i
.PHONY : Sources/Engine/Engine.i

# target to preprocess a source file
Sources/Engine/Engine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Engine.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Engine.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Engine.cc.i
.PHONY : Sources/Engine/Engine.cc.i

Sources/Engine/Engine.s: Sources/Engine/Engine.cc.s
.PHONY : Sources/Engine/Engine.s

# target to generate assembly for a file
Sources/Engine/Engine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Engine.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Engine.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Engine.cc.s
.PHONY : Sources/Engine/Engine.cc.s

Sources/Engine/RenderSystem/Model.o: Sources/Engine/RenderSystem/Model.cc.o
.PHONY : Sources/Engine/RenderSystem/Model.o

# target to build an object file
Sources/Engine/RenderSystem/Model.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Model.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Model.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Model.cc.o
.PHONY : Sources/Engine/RenderSystem/Model.cc.o

Sources/Engine/RenderSystem/Model.i: Sources/Engine/RenderSystem/Model.cc.i
.PHONY : Sources/Engine/RenderSystem/Model.i

# target to preprocess a source file
Sources/Engine/RenderSystem/Model.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Model.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Model.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Model.cc.i
.PHONY : Sources/Engine/RenderSystem/Model.cc.i

Sources/Engine/RenderSystem/Model.s: Sources/Engine/RenderSystem/Model.cc.s
.PHONY : Sources/Engine/RenderSystem/Model.s

# target to generate assembly for a file
Sources/Engine/RenderSystem/Model.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Model.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Model.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Model.cc.s
.PHONY : Sources/Engine/RenderSystem/Model.cc.s

Sources/Engine/RenderSystem/RenderSystem.o: Sources/Engine/RenderSystem/RenderSystem.cc.o
.PHONY : Sources/Engine/RenderSystem/RenderSystem.o

# target to build an object file
Sources/Engine/RenderSystem/RenderSystem.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/RenderSystem.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/RenderSystem.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/RenderSystem.cc.o
.PHONY : Sources/Engine/RenderSystem/RenderSystem.cc.o

Sources/Engine/RenderSystem/RenderSystem.i: Sources/Engine/RenderSystem/RenderSystem.cc.i
.PHONY : Sources/Engine/RenderSystem/RenderSystem.i

# target to preprocess a source file
Sources/Engine/RenderSystem/RenderSystem.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/RenderSystem.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/RenderSystem.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/RenderSystem.cc.i
.PHONY : Sources/Engine/RenderSystem/RenderSystem.cc.i

Sources/Engine/RenderSystem/RenderSystem.s: Sources/Engine/RenderSystem/RenderSystem.cc.s
.PHONY : Sources/Engine/RenderSystem/RenderSystem.s

# target to generate assembly for a file
Sources/Engine/RenderSystem/RenderSystem.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/RenderSystem.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/RenderSystem.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/RenderSystem.cc.s
.PHONY : Sources/Engine/RenderSystem/RenderSystem.cc.s

Sources/Engine/RenderSystem/Shader.o: Sources/Engine/RenderSystem/Shader.cc.o
.PHONY : Sources/Engine/RenderSystem/Shader.o

# target to build an object file
Sources/Engine/RenderSystem/Shader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Shader.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Shader.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Shader.cc.o
.PHONY : Sources/Engine/RenderSystem/Shader.cc.o

Sources/Engine/RenderSystem/Shader.i: Sources/Engine/RenderSystem/Shader.cc.i
.PHONY : Sources/Engine/RenderSystem/Shader.i

# target to preprocess a source file
Sources/Engine/RenderSystem/Shader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Shader.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Shader.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Shader.cc.i
.PHONY : Sources/Engine/RenderSystem/Shader.cc.i

Sources/Engine/RenderSystem/Shader.s: Sources/Engine/RenderSystem/Shader.cc.s
.PHONY : Sources/Engine/RenderSystem/Shader.s

# target to generate assembly for a file
Sources/Engine/RenderSystem/Shader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Shader.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Shader.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Shader.cc.s
.PHONY : Sources/Engine/RenderSystem/Shader.cc.s

Sources/Engine/RenderSystem/Texture.o: Sources/Engine/RenderSystem/Texture.cc.o
.PHONY : Sources/Engine/RenderSystem/Texture.o

# target to build an object file
Sources/Engine/RenderSystem/Texture.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Texture.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Texture.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Texture.cc.o
.PHONY : Sources/Engine/RenderSystem/Texture.cc.o

Sources/Engine/RenderSystem/Texture.i: Sources/Engine/RenderSystem/Texture.cc.i
.PHONY : Sources/Engine/RenderSystem/Texture.i

# target to preprocess a source file
Sources/Engine/RenderSystem/Texture.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Texture.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Texture.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Texture.cc.i
.PHONY : Sources/Engine/RenderSystem/Texture.cc.i

Sources/Engine/RenderSystem/Texture.s: Sources/Engine/RenderSystem/Texture.cc.s
.PHONY : Sources/Engine/RenderSystem/Texture.s

# target to generate assembly for a file
Sources/Engine/RenderSystem/Texture.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/RenderSystem/Texture.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/RenderSystem/Texture.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/RenderSystem/Texture.cc.s
.PHONY : Sources/Engine/RenderSystem/Texture.cc.s

Sources/Engine/Utils/Config.o: Sources/Engine/Utils/Config.cc.o
.PHONY : Sources/Engine/Utils/Config.o

# target to build an object file
Sources/Engine/Utils/Config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Config.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Config.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Config.cc.o
.PHONY : Sources/Engine/Utils/Config.cc.o

Sources/Engine/Utils/Config.i: Sources/Engine/Utils/Config.cc.i
.PHONY : Sources/Engine/Utils/Config.i

# target to preprocess a source file
Sources/Engine/Utils/Config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Config.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Config.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Config.cc.i
.PHONY : Sources/Engine/Utils/Config.cc.i

Sources/Engine/Utils/Config.s: Sources/Engine/Utils/Config.cc.s
.PHONY : Sources/Engine/Utils/Config.s

# target to generate assembly for a file
Sources/Engine/Utils/Config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Config.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Config.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Config.cc.s
.PHONY : Sources/Engine/Utils/Config.cc.s

Sources/Engine/Utils/Debugger.o: Sources/Engine/Utils/Debugger.cc.o
.PHONY : Sources/Engine/Utils/Debugger.o

# target to build an object file
Sources/Engine/Utils/Debugger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Debugger.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Debugger.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Debugger.cc.o
.PHONY : Sources/Engine/Utils/Debugger.cc.o

Sources/Engine/Utils/Debugger.i: Sources/Engine/Utils/Debugger.cc.i
.PHONY : Sources/Engine/Utils/Debugger.i

# target to preprocess a source file
Sources/Engine/Utils/Debugger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Debugger.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Debugger.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Debugger.cc.i
.PHONY : Sources/Engine/Utils/Debugger.cc.i

Sources/Engine/Utils/Debugger.s: Sources/Engine/Utils/Debugger.cc.s
.PHONY : Sources/Engine/Utils/Debugger.s

# target to generate assembly for a file
Sources/Engine/Utils/Debugger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Debugger.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Debugger.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Debugger.cc.s
.PHONY : Sources/Engine/Utils/Debugger.cc.s

Sources/Engine/Utils/Logger.o: Sources/Engine/Utils/Logger.cc.o
.PHONY : Sources/Engine/Utils/Logger.o

# target to build an object file
Sources/Engine/Utils/Logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Logger.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Logger.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Logger.cc.o
.PHONY : Sources/Engine/Utils/Logger.cc.o

Sources/Engine/Utils/Logger.i: Sources/Engine/Utils/Logger.cc.i
.PHONY : Sources/Engine/Utils/Logger.i

# target to preprocess a source file
Sources/Engine/Utils/Logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Logger.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Logger.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Logger.cc.i
.PHONY : Sources/Engine/Utils/Logger.cc.i

Sources/Engine/Utils/Logger.s: Sources/Engine/Utils/Logger.cc.s
.PHONY : Sources/Engine/Utils/Logger.s

# target to generate assembly for a file
Sources/Engine/Utils/Logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Sources/Engine/Utils/Logger.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Engine/Utils/Logger.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Engine/Utils/Logger.cc.s
.PHONY : Sources/Engine/Utils/Logger.cc.s

Sources/Examples/Sandbox/Main.o: Sources/Examples/Sandbox/Main.cc.o
.PHONY : Sources/Examples/Sandbox/Main.o

# target to build an object file
Sources/Examples/Sandbox/Main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Examples/Sandbox/Main.cc.o
.PHONY : Sources/Examples/Sandbox/Main.cc.o

Sources/Examples/Sandbox/Main.i: Sources/Examples/Sandbox/Main.cc.i
.PHONY : Sources/Examples/Sandbox/Main.i

# target to preprocess a source file
Sources/Examples/Sandbox/Main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Examples/Sandbox/Main.cc.i
.PHONY : Sources/Examples/Sandbox/Main.cc.i

Sources/Examples/Sandbox/Main.s: Sources/Examples/Sandbox/Main.cc.s
.PHONY : Sources/Examples/Sandbox/Main.s

# target to generate assembly for a file
Sources/Examples/Sandbox/Main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sandbox.dir/build.make CMakeFiles/Sandbox.dir/Sources/Examples/Sandbox/Main.cc.s
.PHONY : Sources/Examples/Sandbox/Main.cc.s

Sources/Examples/debug_sources/test.o: Sources/Examples/debug_sources/test.cc.o
.PHONY : Sources/Examples/debug_sources/test.o

# target to build an object file
Sources/Examples/debug_sources/test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Examples/debug_sources/test.cc.o
.PHONY : Sources/Examples/debug_sources/test.cc.o

Sources/Examples/debug_sources/test.i: Sources/Examples/debug_sources/test.cc.i
.PHONY : Sources/Examples/debug_sources/test.i

# target to preprocess a source file
Sources/Examples/debug_sources/test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Examples/debug_sources/test.cc.i
.PHONY : Sources/Examples/debug_sources/test.cc.i

Sources/Examples/debug_sources/test.s: Sources/Examples/debug_sources/test.cc.s
.PHONY : Sources/Examples/debug_sources/test.s

# target to generate assembly for a file
Sources/Examples/debug_sources/test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_sources.dir/build.make CMakeFiles/debug_sources.dir/Sources/Examples/debug_sources/test.cc.s
.PHONY : Sources/Examples/debug_sources/test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Sandbox"
	@echo "... debug_sources"
	@echo "... engine"
	@echo "... Sources/Engine/AssetSystem/AssetSystem.o"
	@echo "... Sources/Engine/AssetSystem/AssetSystem.i"
	@echo "... Sources/Engine/AssetSystem/AssetSystem.s"
	@echo "... Sources/Engine/Camera/Camera.o"
	@echo "... Sources/Engine/Camera/Camera.i"
	@echo "... Sources/Engine/Camera/Camera.s"
	@echo "... Sources/Engine/Engine.o"
	@echo "... Sources/Engine/Engine.i"
	@echo "... Sources/Engine/Engine.s"
	@echo "... Sources/Engine/RenderSystem/Model.o"
	@echo "... Sources/Engine/RenderSystem/Model.i"
	@echo "... Sources/Engine/RenderSystem/Model.s"
	@echo "... Sources/Engine/RenderSystem/RenderSystem.o"
	@echo "... Sources/Engine/RenderSystem/RenderSystem.i"
	@echo "... Sources/Engine/RenderSystem/RenderSystem.s"
	@echo "... Sources/Engine/RenderSystem/Shader.o"
	@echo "... Sources/Engine/RenderSystem/Shader.i"
	@echo "... Sources/Engine/RenderSystem/Shader.s"
	@echo "... Sources/Engine/RenderSystem/Texture.o"
	@echo "... Sources/Engine/RenderSystem/Texture.i"
	@echo "... Sources/Engine/RenderSystem/Texture.s"
	@echo "... Sources/Engine/Utils/Config.o"
	@echo "... Sources/Engine/Utils/Config.i"
	@echo "... Sources/Engine/Utils/Config.s"
	@echo "... Sources/Engine/Utils/Debugger.o"
	@echo "... Sources/Engine/Utils/Debugger.i"
	@echo "... Sources/Engine/Utils/Debugger.s"
	@echo "... Sources/Engine/Utils/Logger.o"
	@echo "... Sources/Engine/Utils/Logger.i"
	@echo "... Sources/Engine/Utils/Logger.s"
	@echo "... Sources/Examples/Sandbox/Main.o"
	@echo "... Sources/Examples/Sandbox/Main.i"
	@echo "... Sources/Examples/Sandbox/Main.s"
	@echo "... Sources/Examples/debug_sources/test.o"
	@echo "... Sources/Examples/debug_sources/test.i"
	@echo "... Sources/Examples/debug_sources/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

